### ISSUE TITLE
I can't create a pull request

### ISSUE THREAD

**Issue by thetaungg** [zero-to-mastery/CSS_Grid_LearnGame#15]
I worked on a new feature and when I try to create pull request by pushing the branch I created. It says 'remote: Permission to zero-to-mastery/CSS_Grid_LearnGame.git denied to thetaung123'.

I've contributed to a few ZTM repos before. Only now I see this kind of error. 
Can anyone help me fix it?

**Comment by thetaung123** [comment]
I forked the repository
